version: '2'
services:
    db: 
        platform: linux/x86_64
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: parking-db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3307:3306"
    web:
        platform: linux/x86_64
        build: .
        ports:
            - "3000:3000"
        volumes:
            - .:/app
        depends_on:
            - db
        environment:
            RAILS_ENV: development
