default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 0.0.0.0
  port: 3307
  socket: /var/run/mysqld/mysqld.sock
  database: parking-db
  username: user
  password: password

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

