default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: user
  password: password
  host: db
  socket: /var/run/mysqld/mysqld.sock
  database: parking-db

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

